---
- name: Set up a new remote or local Mac for Python developer
  hosts: all
  vars:
    homebrew_prefix: "{{ (ansible_machine == 'arm64') | ternary('/opt/homebrew', '/usr/local') }}"
    homebrew_install_path: "{{ homebrew_prefix }}{{ '/Homebrew' if ansible_machine != 'arm64' }}"
    homebrew_installed_packages:
      - python@3.8
      - python-packaging  # Required for Ansible
      - gcc               # GNU compiler collection
      - ansible
      - wget              # File downloading from web
      - tree              # Displays directory path as tree
      - htop              # User friendly alternative to 'top'
    homebrew_cask_apps:
      - docker
      - iterm2
      - visual-studio-code
    homebrew_cask_accept_external_apps: true
  roles:
    - geerlingguy.mac.homebrew

  tasks:
    - name: Install Python developer packages
      pip:
        name:
          - black       # Code formatter
          - flake8      # Linting tool
          - pylint      # Code analysis
          - sphinx      # Documentation generator
          - pytest      # Testing framework
          - virtualenv  # Virtual environments
        state: latest
        executable: /opt/homebrew/bin/pip3.8
