all:
  children:
    localhost:
    remotehosts:
localhost:
  hosts:
    local:
      ansible_connection: local
remotehosts:
  hosts:
    network_remote_host_2: # For use with developer macs
      ansible_host: remote.host.2.ip
      ansible_connection: ssh
      ansible_user: your_username
      ansible_ssh_password: your_password
