all:
  children:
    localhost:
    remotehosts:
localhost:
  hosts:
    local:
      ansible_connection: local
remotehosts:
  hosts:
    aws_remote_host_1: # For use with AWS dedicated mac2.metal instances
      ansible_host: your.dns.name
      ansible_connection: ssh
      ansible_user: your-username
      ansible_ssh_private_key_file: ~/Secrets/my-private-key.pem
